name: 'Get Matrix from JSON'
description: 'Gets a GitHub Action Matrix array for every item in a JSON'
author: 'Surnet'
branding:
  icon: 'shuffle'
  color: 'orange'
inputs:
  filepath:
    required: true
    description: 'Path to the JSON file'
    default: './matrix.json'
outputs:
  matrix:
    description: 'GitHub Action Matrix'
runs:
  using: 'node16'
  main: 'dist/index.js'
